### ISSUE TITLE
Add Shadow styling options

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Plugin.Maui.Crosswind#2]
_Currently we cannot add any shadow related styling, due to the CSS support not being there for .NET MAUI._

Ideally we'd be able to style any visual elements shadow through a number of possible CSS classes:

```css
// Make more of these shadow-xs, shadow-sm, shadow-lg etc. etc.
.shadow-md {
    shadow-offset: 4 4; 
    shadow-opacity: 0.5; 
    shadow-radius: 8;
}

// Make color variants for the entire color spectrum.
.shadow-black {
    shadow-color: #000000;
}
```
